export const RPG_ITEMS = {
  normieFish: 'normie fish',
  goldenFish: 'golden fish',
  epicFish: 'epic fish',
  superFish: 'super fish',
  woodenLog: 'wooden log',
  epicLog: 'epic log',
  superLog: 'super log',
  megaLog: 'mega log',
  hyperLog: 'hyper log',
  ultraLog: 'ultra log',
  apple: 'apple',
  banana: 'banana',
  watermelon: 'watermelon',
  ruby: 'ruby',
  potato: 'potato',
  carrot: 'carrot',
  bread: 'bread',
  flask: 'flask',
  wolfSkin: 'wolf skin',
  zombieEye: 'zombie eye',
  unicornHorn: 'unicorn horn',
  mermaidHair: 'mermaid hair',
  chip: 'chip',
  darkEnergy: 'dark energy',
  lifePotion: 'life potion',
  timeKey: 'time key',
  arenaCookie: 'arena cookie',
  timeCookie: 'time cookie',
  epicBerry: 'epic berry',
  lotteryTicket: 'lottery ticket',
  guildRing: 'guild ring',
  commonLootbox: 'common lootbox',
  uncommonLootbox: 'uncommon lootbox',
  rareLootbox: 'rare lootbox',
  epicLootbox: 'epic lootbox',
  edgyLootbox: 'edgy lootbox',
  omegaLootbox: 'omega lootbox',
  godlyLootbox: 'godly lootbox',
  ultimateLog: 'ultimate log',
  anniversaryLootbox: 'anniversary lootbox',
  compensationLootbox: 'compensation lootbox',
  seed: 'seed',
  breadSeed: 'bread seed',
  potatoSeed: 'potato seed',
  carrotSeed: 'carrot seed',
  dragonScale: 'dragon scale',
  dragonEssence: 'dragon essence',
  coinTrumpet: 'coin trumpet',
  epicSeed: 'epic seed',
  ultraBait: 'ultra bait',
  arenaToken: 'arena token',
  sleepetPotion: 'sleepet potion',
  partyPopper: 'party popper',
} as const;

export const RPG_EPIC_ITEM_TYPES = {
  coinTrumpet: 'coin trumpet',
  epicSeed: 'epic seed',
  ultraBait: 'ultra bait',
} as const;
