export const RPG_HUNT_MONSTER_AREA_LIST = {
  a1: ['WOLF', 'GOBLIN', 'SLIME'],
  a2: ['NYMPH', 'SKELETON'],
  a3: ['ZOMBIE', 'BABY DEMON', 'GHOST'],
  a4: ['WITCH', 'IMP'],
  a5: ['UNICORN', 'GHOUL', 'GIANT SCORPION'],
  a6: ['SORCERER', 'BABY ROBOT'],
  a7: ['MERMAID', 'CECAELIA', 'GIANT PIRANHA'],
  a8: ['GIANT CROCODILE', 'NEREID'],
  a9: ['KILLER ROBOT', 'HARPY', 'DEMON'],
  a10: ['MANTICORE', 'DULLAHAN'],
  a11: ['BABY DRAGON', 'SCALED BABY DRAGON', 'YOUNG DRAGON'],
  a12: ['KID DRAGON', 'SCALED KID DRAGON', 'NOT SO YOUNG DRAGON'],
  a13: ['TEEN DRAGON', 'SCALED TEEN DRAGON', 'DEFINITELY NOT YOUNG DRAGON'],
  a14: ['ADULT DRAGON', 'SCALED ADULT DRAGON', 'NOT YOUNG AT ALL DRAGON'],
  a15: ['OLD DRAGON', 'SCALED OLD DRAGON', 'HOW DO YOU DARE CALL THIS DRAGON'],
  top: ['EPIC NPC'],
  a16: ['ABYSS BUG', 'VOID SHARD', 'VOID PARTICLES', 'VOID FRAGMENT'],
  a17: ['SHADOW HANDS', 'NOTHING'],
  a18: [],
  a19: ['FLYING SAUCER', 'NEUTRON STAR', 'ASTEROID'],
  a20: [],
  valentine: ['PINK WOLF'],
  christmas: ['CHRISTMAS REINDEER', 'ELF', 'SNOWMAN', 'CHRISTMAS SLIME'],
};

export const RPG_ADVENTURE_MONSTER_AREA_LIST = {
  a1: ['BUNCH OF BEES', 'GIANT SPIDER', 'MUTANT WATER BOTTLE'],
  a2: ['HYPER GIANT BOWL', 'OGRE', 'DARK KNIGHT'],
  a3: ['WEREWOLF', 'CENTAUR', 'MUTANT SHOE'],
  a4: ['CHIMERA', 'GOLEM', 'HYPER GIANT AERONAUTICAL ENGINE'],
  a5: ['MAMMOTH', 'MUTANT \'ESC\' KEY', 'ENT'],
  a6: ['DINOSAUR', 'CYCLOP', 'HYPER GIANT DOOR'],
  a7: ['ATTACK HELICOPTER', 'MUTANT BOOK', 'HYDRA'],
  a8: ['HYPER GIANT CHEST', 'KRAKEN', 'LEVIATHAN'],
  a9: ['MUTANT BACKPACK', 'WAR TANK', 'WYRM'],
  a10: ['HYPER GIANT TOILET', 'TITAN', 'TYPHON'],
  a11: ['ANCIENT DRAGON', 'MUTANT DRAGON'],
  a12: ['EVEN MORE ANCIENT DRAGON', 'HYPER GIANT DRAGON'],
  a13: [
    'ANCIENTEST DRAGON',
    'ANOTHER MUTANT DRAGON LIKE IN AREA 11 BUT STRONGER',
  ],
  a14: [
    'just purple DRAGON',
    'YES, AS YOU EXPECTED, ANOTHER HYPER GIANT DRAGON BUT OP ETC',
  ],
  a15: ['MUTANTEST DRAGON', 'i have no more ideas DRAGON'],
  top: ['EPIC NPC'],
  a16: [
    'SHADOW CREATURE',
    'SHADOW ENTITY',
    'ABYSS WORM',
    'VOID CUBE',
    'VOID CONE',
  ],
  a17: [],
  a18: [],
  a19: ['SUPERNOVA'],
  christmas: ['YETI', 'KRAMPUS', 'HYPER GIANT ICE BLOCK'],
  halloween: ['bat slime'],
};

export const HUNT_MONSTER_LIST = Object.values(
  RPG_HUNT_MONSTER_AREA_LIST,
).flat();

export const ADVENTURE_MONSTER_LIST = Object.values(
  RPG_ADVENTURE_MONSTER_AREA_LIST,
).flat();
